### ISSUE TITLE
Signet support

### ISSUE THREAD

**Issue by pepper28** [Polve/bitcoin-rpc-client#124]
I looked at your BitcoinJSONRPCClient Class and you have main, testnet, and regtest but no Signet support.  Can you update the package?

**Comment by Polve** [comment]
you should be able to use signet without any problem, just change the port you are connecting to.
What are your problems?

**Comment by pepper28** [comment]
Polve, Thanks very much for your reply.  Here is more detail of the problem I'm encountering.  I thought the problem was the test faucet of Signet but I’m not sure why when I pass new BigDecimal (.1) I receive the following error message.  “response code: 500 responseMessage Internal Server Error, response: {"result":null,"error":{"code":-3,"message":"Invalid amount"},"id":"1"} “  In my Bitcoin core readings I saw it mentioned the precision is 8 positions and my big decimal is  0.1000000000000000055511151231257827021181583404541015625 for a .1 request.  How do you handle this in your method SendToAddress.  Here is my code

URL url = new URL("http://" + user + ':' + password + "@" + host + ":" + port + "/");

BitcoinJSONRPCClient bitcoinClient = new BitcoinJSONRPCClient(url);	bitcoinClient.sendToAddress("tb1qzp5424a24fvdtecdvvftgzf34",new BigDecimal(.1));

**Comment by pepper28** [comment]
I utilized Bitcoin-CLI and pass the request to send 0.1 amount to a target wallet with complete success.  I then tried again using the bitcoin-rpc-client with the new BigDecimal (0.1) and it failed again with the  Error, response: {"result":null,"error":{"code":-3,"message":"Invalid amount"},"id":"1"} “ response

**Comment by pepper28** [comment]
I discovered my error.  One must encase the number in double-quotes.  That seemed counter-intuitive to me because it is a number, but further research uncovered my omission.  Thanks for all your help.

**Comment by Polve** [comment]
Right, my bad for not detecting the error too.
Thanks for the follow-up.
