### ISSUE TITLE
Add support for missing methods

### ISSUE THREAD

**Issue by tdiesler** [Polve/bitcoin-rpc-client#73]
### Missing blockchain methods supported in 0.17.0 are ...

   * getblockheader "hash" ( verbose )
   * getblockstats hash_or_height ( stats )
   * getchaintips
   * getchaintxstats ( nblocks blockhash )
   * getmempoolancestors txid (verbose)
   * getmempooldescendants txid (verbose)
   * getmempoolentry txid
   * getmempoolinfo
   * gettxoutproof ["txid",...] ( blockhash )
   * preciousblock "blockhash"
   * pruneblockchain
   * savemempool
   * scantxoutset <action> ( <scanobjects> )
   * verifytxoutproof "proof"

### Missing control methods supported in 0.17.0 are ...

   * getmemoryinfo ("mode")
   * logging ( <include> <exclude> )
   * uptime

### Missing mining methods supported in 0.17.0 are ...

   * getblocktemplate ( TemplateRequest )
   * prioritisetransaction <txid> <dummy value> <fee delta>

### Missing network methods supported in 0.17.0 are ...

   * clearbanned
   * disconnectnode "[address]" [nodeid]
   * listbanned
   * setban "subnet" "add|remove" (bantime) (absolute)
   * setnetworkactive true|false

### Missing raw transaction methods supported in 0.17.0 are ...

   * combinepsbt ["psbt",...]
   * combinerawtransaction ["hexstring",...]
   * converttopsbt "hexstring" ( permitsigdata iswitness )
   * createpsbt [{"txid":"id","vout":n},...] [{"address":amount},{"data":"hex"},...] ( locktime ) ( replaceable )
   * decodepsbt "psbt"
   * decoderawtransaction "hexstring" ( iswitness )
   * finalizepsbt "psbt" ( extract )
   * fundrawtransaction "hexstring" ( options iswitness )
   * testmempoolaccept ["rawtxs"] ( allowhighfees )

### Missing util methods supported in 0.17.0 are ...

   * signmessagewithprivkey "privkey" "message"

### Missing wallet methods supported in 0.17.0 are ...

   * abandontransaction "txid"
   * abortrescan
   * bumpfee "txid" ( options ) 
   * createwallet "wallet_name" ( disable_private_keys )
   * getaddressesbylabel "label"
   * getaddressinfo "address"
   * importmulti "requests" ( "options" )
   * importprunedfunds
   * importpubkey "pubkey" ( "label" rescan )
   * listaddressgroupings
   * listlabels ( "purpose" )
   * listwallets
   * loadwallet "filename"
   * removeprunedfunds "txid"
   * rescanblockchain ("start_height") ("stop_height")
   * sendmany "" {"address":amount,...} ( minconf "comment" ["address",...] replaceable conf_target "estimate_mode")
   * sethdseed ( "newkeypool" "seed" )
   * signrawtransactionwithwallet "hexstring" ( [{"txid":"id","vout":n,"scriptPubKey":"hex","redeemScript":"hex"},...] sighashtype )
   * unloadwallet ( "wallet_name" )
   * walletcreatefundedpsbt [{"txid":"id","vout":n},...] [{"address":amount},{"data":"hex"},...] ( locktime ) ( replaceable ) ( options bip32derivs )
   * walletlock
   * walletpassphrasechange "oldpassphrase" "newpassphrase"
   * walletprocesspsbt "psbt" ( sign "sighashtype" bip32derivs )

### Missing ZeroMQ methods supported in 0.17.0 are ...

  * getzmqnotifications

**Comment by cd2357** [comment]
Support for signrawtransactionwithkey came with #99

@tdiesler -- can you please edit the list above and remove this method from there? Thanks.

**Comment by Polve** [comment]
I edited the comment, thanks @cd2357

**Comment by tdiesler** [comment]
out-of-date
